package org.bardframework.form.common;

public enum FieldTypeBase implements FieldType<FieldTypeBase> {
    AVATAR_VIEW,
    CAPTCHA,
    DATE,
    DATE_RANGE,
    DATE_TIME,
    DATE_TIME_RANGE,
    DIVIDER,
    FILE_DOWNLOAD,
    FILE_UPLOAD,
    HTML_EDITOR,
    HTML_VIEW,
    IMAGE_VIEW,
    IMAGE_UPLOAD,
    LIST,
    MESSAGE,
    MULTI_SELECT,
    MULTI_SELECT_SEARCHABLE,
    NEW_PASSWORD,
    NUMBER,
    NUMBER_RANGE,
    PASSWORD,
    PAYMENT,
    READONLY,
    SINGLE_CHECKBOX,
    SINGLE_SELECT,
    SINGLE_SELECT_SEARCHABLE,
    TEXT_AREA,
    TEXT,
    TIME,
    TIME_RANGE,
}
