package org.bardframework.form;

public enum FieldType {
    TEXT, PASSWORD, NEW_PASSWORD, TEXT_AREA,
    SELECT, RADIO_BUTTON, CHECKBOX,
    DATE_JALALI, DATE_GREGORIAN,
    FILE, AVATAR, IMAGE, FILE_UPLOAD,
    DIVIDER, CAPTCHA, MESSAGE,
    PAYMENT, TABLE
}
