package org.bardframework.form.field.input;

import org.bardframework.form.field.FieldType;

public enum InputFieldType implements FieldType {
    AVATAR_SELECT,
    CAPTCHA,
    CARD,
    CHECKBOX,
    COUNTRY_SELECT,
    COUNTRY_MULTI_SELECT,
    DATE,
    DATE_TIME,
    FILE_UPLOAD,
    HTML_EDITOR,
    ICON_SELECT,
    IMAGE_UPLOAD,
    IP4,
    IP6,
    LIST,
    LOCALE_SELECT,
    LOCALE_MULTI_SELECT,
    LOCATION_SELECT,
    MULTI_SELECT,
    MULTI_SELECT_SEARCHABLE,
    NEW_PASSWORD,
    NUMBER,
    OTP,
    PASSWORD,
    PHONE_NUMBER,
    SINGLE_SELECT,
    SINGLE_SELECT_SEARCHABLE,
    SSOTP,
    SWITCH_BUTTON,
    TEXT,
    TEXT_AREA,
    TIME,
    TIME_ZONE_SELECT,
    WYSIWYG,
}
